#!/bin/bash
# Code Generated by Sidekick is for learning and experimentation purposes only. 

# Function to check Jira status
check_jira_status() {
    systemctl is-active jira
}

# Start Jira service
systemctl start jira

# Check Jira status 3-4 times with 5 seconds interval
for i in {1..4}; do
    status=$(check_jira_status)
    if [ "$status" == "active" ]; then
        echo "Jira has been successfully started."
        exit 0
    elif [ "$status" == "failed" ]; then
        echo "Jira failed to start. Attempt $i of 4."
    else
        echo "Unexpected status: $status. Please check Jira manually."
        exit 1
    fi
    sleep 5
done

# If the loop completes without starting Jira
echo "Could not start Jira after multiple attempts. Please check manually."
exit 1
