# Code Generated by Sidekick is for learning and experimentation purposes only. 

$server = ""  # Replace with your server address
$username = ""  # Replace with your username
$password = ""  # Replace with your password
$jiraService = "jira"

# Function to run a command via SSH
function Run-SSHCommand($command) {
    try {
        $sshSession = New-SSHSession -ComputerName $server -Credential (New-Object PSCredential($username, (ConvertTo-SecureString $password -AsPlainText -Force)))
        Write-Output "SSH session secured successfully."
        $result = Invoke-SSHCommand -SessionId $sshSession.SessionId -Command $command
        Remove-SSHSession -SessionId $sshSession.SessionId
        return $result.Output
    } catch {
        Write-Error "Error occurred while executing command: $_"
        exit 1
    }
}

# Function to check Jira status
function Check-JiraStatus {
    $statusCommand = "sudo systemctl is-active $jiraService"
    return Run-SSHCommand $statusCommand
}

# Start Jira service
Run-SSHCommand "sudo systemctl start $jiraService"

# Check Jira status 3-4 times with 5 seconds interval
for ($i = 1; $i -le 4; $i++) {
    $status = Check-JiraStatus
    if ($status -eq "active") {
        Write-Output "Jira has been successfully started."
        exit 0
    } elseif ($status -eq "failed") {
        Write-Output "Jira is not running. Attempt $i of 4."
    } else {
        Write-Output "Unexpected status: $status. Please check Jira manually."
        exit 1
    }
    Start-Sleep -Seconds 5
}

# If Jira still cannot be started
Write-Output "Could not start Jira after multiple attempts. Please check manually."
exit 1
