#!/bin/bash
# Code Generated by Sidekick is for learning and experimentation purposes only. 

# Function to check Jira status
check_jira_status() {
    systemctl is-active jira
}

# Stop Jira service
systemctl stop jira

# Check Jira status 3-4 times with 5 seconds interval
for i in {1..4}; do
    status=$(check_jira_status)
    if [ "$status" == "failed" ]; then
        echo "Jira has been successfully stopped."
        exit 0
    elif [ "$status" == "active" ]; then
        echo "Jira is still running. Attempt $i of 4."
    else
        echo "Unexpected status: $status. Please check Jira manually."
        exit 1
    fi
    sleep 5
done

# If the loop completes without stopping Jira
echo "Could not stop Jira after multiple attempts. Please check manually."
exit 1



#This script will:

#Attempt to stop the Jira service using systemctl stop jira.
#Check the status of the Jira service up to 4 times with a 5-second interval between checks.
#If the status is failed, it will confirm that Jira has been successfully stopped.
#If the status is active, it will indicate that Jira is still running and retry.
#If the status is anything else, it will throw an error and exit.
#If Jira cannot be stopped after multiple attempts, it will throw an error and exit.

